project:
  type: book
  output-dir: docs
  
book:
  title: "Essays"
  author: "Rafael C. Alvarado"
  date: "5/8/2023"
  chapters:
    - index.qmd
    - part: "Data Science"
      chapters:
        - essays/history-of-ds/ds-from-1963-to-2012.qmd
    - part: "Digital Humanities"
    - part: "Notes"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
