# The Pluralist's Delimma

Pluralism is the de facto foundation of democracy.

- Pluralism is the belief that a society must not be founded on any single belief system, such as Christianity, but on many and none.

- Democracy here means something more than universal voting (suffrage).

- It is liberal democracy.

- Cite Fukuyama and Anderson.

- Pluralism is the presumptive condition of possibility of a liberal democracy.

But is also true that the holy grail of a political system is the creation of community.

- Pluralism may be the cause, but community is the expected outcome.

- Pretty much all political ideologies have community as their goal.

- It's not the only goal in some cases, but it is always there.


The problem is that the conditions for community contradict the premise of pluralism.

- Tonnies is still correct -- communities are based in shared belief.

- There is ample evidence to support this.

- The hard truth is the people flourish in spaces where they share values, outlook, etc.

- Rituals create and reproduce this sense.


The exception is the cosmopolitan ethos ...

- But this is just society -- founded on interest, not belief.


In the face of this delimma, one response has been to downplay commmunity and to upgrade society.

- In this view, society -- say, in the form of Wellman's networked individualism -- is OK, good enough.

- But even here, there is community and belief.

- Pluralism itself is a belief.


This never more clear than when pluralism is injected into the nucleus of community practices.

- This is most evident in gender.

- The quintessential pluralist platform is LGTPQ ...

- Also, DEI

- Critics of these movements note the paradox -- diversity in some contexts, radical identity in others.

So, what is to be done?